"""Focused tests for the isolated node-workflow documentation proposal."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

EXAMPLE_AGENT_ROOT = Path(__file__).resolve().parents[2]
if str(EXAMPLE_AGENT_ROOT) not in sys.path:
    sys.path.insert(0, str(EXAMPLE_AGENT_ROOT))

from scripts import node_workflow_docs  # noqa: E402


def test_wave2_review_example_inventory_is_fresh() -> None:
    path = node_workflow_docs.check_workflow_doc("wave2_synthesis")

    assert path.name == "workflow.md"
    assert "review-example" in path.as_posix()


def test_cli_accepts_explicit_read_only_check(capsys: pytest.CaptureFixture[str]) -> None:
    assert node_workflow_docs.main(["--check"]) == 0

    assert "Workflow documentation checked:" in capsys.readouterr().out


def test_inventory_is_derived_from_current_prompt_cases_and_topology() -> None:
    inventory = node_workflow_docs.render_inventory("wave2_synthesis")

    assert "wave2-synthesis/synthesis" in inventory
    assert "build_synthesis_prompt" in inventory
    assert "wave2-evidence-synthesis" in inventory
    assert "wave2_synthesis:evidence_needed" in inventory
    assert "targeted_evidence" in inventory


def test_replacing_inventory_preserves_authored_prose_byte_for_byte() -> None:
    document = (
        "authored before\n"
        f"{node_workflow_docs.BEGIN_MARKER}\n"
        "stale generated bytes\n"
        f"{node_workflow_docs.END_MARKER}\n"
        "authored after\n"
    )

    refreshed = node_workflow_docs.replace_generated_region(document, "fresh generated bytes\n")

    assert refreshed.startswith("authored before\n")
    assert refreshed.endswith("\nauthored after\n")
    assert "stale generated bytes" not in refreshed
    assert "fresh generated bytes" in refreshed


@pytest.mark.parametrize(
    "document",
    (
        "no markers\n",
        f"{node_workflow_docs.BEGIN_MARKER}\nmissing end\n",
        (f"{node_workflow_docs.BEGIN_MARKER}\n{node_workflow_docs.BEGIN_MARKER}\n{node_workflow_docs.END_MARKER}\n"),
    ),
)
def test_invalid_generated_markers_fail_closed(document: str) -> None:
    with pytest.raises(node_workflow_docs.WorkflowDocError, match="workflow_markers_invalid"):
        node_workflow_docs.replace_generated_region(document, "fresh\n")


def test_identity_mismatch_is_not_rewritten(tmp_path: Path) -> None:
    target = tmp_path / "workflow.md"
    target.write_text(
        '<!-- node-workflow-card: {"schema_version":1,"workflow_id":"node-workflow/wave1",'
        '"logical_node":"wave1","classification":"node-agent"} -->\n'
        f"{node_workflow_docs.BEGIN_MARKER}\nold\n{node_workflow_docs.END_MARKER}\n",
        encoding="utf-8",
    )
    before = target.read_bytes()

    with pytest.raises(node_workflow_docs.WorkflowDocError, match="workflow_identity_mismatch"):
        node_workflow_docs.write_workflow_doc("wave2_synthesis", path=target)

    assert target.read_bytes() == before
