"""Deterministic semantic topology snapshot rendering.

@impl REG-005
"""

from __future__ import annotations

from deerflow_deep_research.graph.topology import LOGICAL_NODES, NORMALIZED_EDGES, TERMINALS


def render_topology_snapshot() -> str:
    lines = [
        "# Deep Research Logical Topology",
        "",
        "> Generated by `uv run python scripts/render_topology.py`; do not edit manually.",
        "",
        "## Nodes",
        "",
        *(f"- `{name}`" for name in LOGICAL_NODES),
        "",
        "## Terminals",
        "",
        *(f"- `{name}`" for name in sorted(TERMINALS)),
        "",
        "## Semantic edges",
        "",
        "```text",
        *(f"{edge.source} --{edge.route}--> {edge.target}" for edge in NORMALIZED_EDGES),
        "```",
        "",
    ]
    return "\n".join(lines)


__all__ = ["render_topology_snapshot"]
