#!/usr/bin/env python3
"""Review-only prototype for node-local workflow documentation.

The adapter reads current prompt-catalog and topology owners, then checks or replaces
only one explicitly marked inventory region in the isolated review example. Runtime
never imports this file.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

EXAMPLE_AGENT_ROOT = Path(__file__).resolve().parents[1]
BEGIN_MARKER = "<!-- BEGIN GENERATED: NODE-WORKFLOW-INVENTORY -->"
END_MARKER = "<!-- END GENERATED: NODE-WORKFLOW-INVENTORY -->"
_IDENTITY = re.compile(r"[a-z0-9_]+")
_METADATA = re.compile(r"<!-- node-workflow-card: (\{.*\}) -->")

# PromptCatalogCase currently exposes an output slug rather than canonical logical_node.
# A reviewed implementation should add that field or retain this closed, tested mapping.
CATALOG_NODE_TO_LOGICAL = {
    "hitl1": "hitl1",
    "targeted-evidence": "targeted_evidence",
    "topic-planning": "topic_planning",
    "wave0": "wave0",
    "wave1": "wave1",
    "wave2-synthesis": "wave2_synthesis",
}


class WorkflowDocError(RuntimeError):
    """A bounded identity, marker, or freshness failure."""

    def __init__(self, code: str, detail: str) -> None:
        super().__init__(f"{code}: {detail}")
        self.code = code
        self.detail = detail


@dataclass(frozen=True, order=True)
class BranchInventory:
    case_id: str
    builder_id: str
    capability_id: str
    requested_tools: str


@dataclass(frozen=True, order=True)
class EdgeInventory:
    source: str
    route: str
    target: str


def workflow_path(logical_node: str) -> Path:
    """Return the fixed review-example path for one canonical logical node."""

    if not isinstance(logical_node, str) or _IDENTITY.fullmatch(logical_node) is None:
        raise WorkflowDocError("workflow_identity_invalid", "logical node must use [a-z0-9_]+")
    return EXAMPLE_AGENT_ROOT / "src" / "deerflow_deep_research" / "graph" / "nodes" / logical_node / "workflow.md"


def inventory_from_current_owners(
    logical_node: str,
) -> tuple[tuple[BranchInventory, ...], tuple[EdgeInventory, ...]]:
    """Read current branch/request and semantic-edge owners without invoking a model."""

    from deerflow_deep_research.graph.prompt_catalog import prompt_catalog_cases
    from deerflow_deep_research.graph.topology import NORMALIZED_EDGES

    branches: list[BranchInventory] = []
    for case in prompt_catalog_cases():
        if CATALOG_NODE_TO_LOGICAL.get(case.node_name) != logical_node:
            continue
        request = case.build_request()
        capability_ref = request.capability_ref
        branches.append(
            BranchInventory(
                case_id=case.case_id,
                builder_id=case.builder_id,
                capability_id="none" if capability_ref is None else capability_ref.capability_id,
                requested_tools="enabled" if request.tools_enabled else "forbidden",
            )
        )
    edges = tuple(
        EdgeInventory(source=edge.source, route=edge.route, target=edge.target)
        for edge in NORMALIZED_EDGES
        if edge.source == logical_node
    )
    if not branches:
        raise WorkflowDocError("workflow_branches_missing", f"no prompt cases for {logical_node}")
    if not edges:
        raise WorkflowDocError("workflow_edges_missing", f"no semantic edges for {logical_node}")
    return tuple(sorted(branches)), tuple(sorted(edges))


def render_inventory(logical_node: str) -> str:
    """Render the exact generated bytes between the two fixed markers."""

    branches, edges = inventory_from_current_owners(logical_node)
    branch_rows = "\n".join(
        f"| `{item.case_id}` | `{item.builder_id}` | `{item.capability_id}` | {item.requested_tools} |"
        for item in branches
    )
    edge_rows = "\n".join(f"| `{item.source}:{item.route}` | `{item.target}` |" for item in edges)
    return (
        "| Direct branch | Request builder | Capability | Requested tools |\n"
        "| --- | --- | --- | --- |\n"
        f"{branch_rows}\n\n"
        "| Semantic edge | Normalized target |\n"
        "| --- | --- |\n"
        f"{edge_rows}\n"
    )


def replace_generated_region(document: str, generated: str) -> str:
    """Replace exactly one inventory region while preserving all authored bytes."""

    if document.count(BEGIN_MARKER) != 1 or document.count(END_MARKER) != 1:
        raise WorkflowDocError("workflow_markers_invalid", "expected exactly one ordered marker pair")
    before, _, remainder = document.partition(BEGIN_MARKER)
    _old_region, separator, after = remainder.partition(END_MARKER)
    if not separator:
        raise WorkflowDocError("workflow_markers_invalid", "end marker must follow begin marker")
    body = generated if generated.endswith("\n") else generated + "\n"
    return f"{before}{BEGIN_MARKER}\n{body}{END_MARKER}{after}"


def _validate_metadata(document: str, logical_node: str) -> None:
    first_line = document.splitlines()[0] if document else ""
    match = _METADATA.fullmatch(first_line)
    if match is None:
        raise WorkflowDocError("workflow_metadata_invalid", "first line must contain card metadata")
    try:
        metadata = json.loads(match.group(1))
    except json.JSONDecodeError as exc:
        raise WorkflowDocError("workflow_metadata_invalid", "metadata must be valid JSON") from exc
    expected = {
        "workflow_id": f"node-workflow/{logical_node}",
        "logical_node": logical_node,
        "classification": "node-agent",
    }
    for key, value in expected.items():
        if metadata.get(key) != value:
            raise WorkflowDocError("workflow_identity_mismatch", f"{key} must equal {value!r}")


def check_workflow_doc(logical_node: str, *, path: Path | None = None) -> Path:
    """Check identity and generated freshness without writing."""

    target = path or workflow_path(logical_node)
    document = target.read_text(encoding="utf-8")
    _validate_metadata(document, logical_node)
    expected = replace_generated_region(document, render_inventory(logical_node))
    if document != expected:
        raise WorkflowDocError("workflow_inventory_stale", f"generated inventory differs: {target}")
    return target


def write_workflow_doc(logical_node: str, *, path: Path | None = None) -> Path:
    """Atomically refresh only the generated region in one regular Markdown file."""

    target = path or workflow_path(logical_node)
    if target.is_symlink() or not target.is_file():
        raise WorkflowDocError("workflow_path_unsafe", "target must be an existing regular file")
    document = target.read_text(encoding="utf-8")
    _validate_metadata(document, logical_node)
    refreshed = replace_generated_region(document, render_inventory(logical_node))
    if refreshed == document:
        return target
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as temporary:
            temporary.write(refreshed)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, target)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise
    return check_workflow_doc(logical_node, path=target)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("logical_node", nargs="?", default="wave2_synthesis")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--check", action="store_true", help="verify without writing (default)")
    action.add_argument("--write", action="store_true", help="refresh the generated region")
    args = parser.parse_args(argv)
    try:
        target = write_workflow_doc(args.logical_node) if args.write else check_workflow_doc(args.logical_node)
    except (OSError, WorkflowDocError) as exc:
        parser.error(str(exc))
    action = "refreshed" if args.write else "checked"
    print(f"Workflow documentation {action}: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
